// Generated by gencpp from file contactile_gripper/ChangeModeResponse.msg
// DO NOT EDIT!


#ifndef CONTACTILE_GRIPPER_MESSAGE_CHANGEMODERESPONSE_H
#define CONTACTILE_GRIPPER_MESSAGE_CHANGEMODERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace contactile_gripper
{
template <class ContainerAllocator>
struct ChangeModeResponse_
{
  typedef ChangeModeResponse_<ContainerAllocator> Type;

  ChangeModeResponse_()
    : response()  {
    }
  ChangeModeResponse_(const ContainerAllocator& _alloc)
    : response(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::contactile_gripper::ChangeModeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::contactile_gripper::ChangeModeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ChangeModeResponse_

typedef ::contactile_gripper::ChangeModeResponse_<std::allocator<void> > ChangeModeResponse;

typedef boost::shared_ptr< ::contactile_gripper::ChangeModeResponse > ChangeModeResponsePtr;
typedef boost::shared_ptr< ::contactile_gripper::ChangeModeResponse const> ChangeModeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::contactile_gripper::ChangeModeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::contactile_gripper::ChangeModeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::contactile_gripper::ChangeModeResponse_<ContainerAllocator1> & lhs, const ::contactile_gripper::ChangeModeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::contactile_gripper::ChangeModeResponse_<ContainerAllocator1> & lhs, const ::contactile_gripper::ChangeModeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace contactile_gripper

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::contactile_gripper::ChangeModeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::contactile_gripper::ChangeModeResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::contactile_gripper::ChangeModeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::contactile_gripper::ChangeModeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::contactile_gripper::ChangeModeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::contactile_gripper::ChangeModeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::contactile_gripper::ChangeModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6de314e2dc76fbff2b6244a6ad70b68d";
  }

  static const char* value(const ::contactile_gripper::ChangeModeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6de314e2dc76fbffULL;
  static const uint64_t static_value2 = 0x2b6244a6ad70b68dULL;
};

template<class ContainerAllocator>
struct DataType< ::contactile_gripper::ChangeModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "contactile_gripper/ChangeModeResponse";
  }

  static const char* value(const ::contactile_gripper::ChangeModeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::contactile_gripper::ChangeModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string response\n"
;
  }

  static const char* value(const ::contactile_gripper::ChangeModeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::contactile_gripper::ChangeModeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChangeModeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::contactile_gripper::ChangeModeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::contactile_gripper::ChangeModeResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTACTILE_GRIPPER_MESSAGE_CHANGEMODERESPONSE_H
