// Generated by gencpp from file contactile_gripper/ChangeMode.msg
// DO NOT EDIT!


#ifndef CONTACTILE_GRIPPER_MESSAGE_CHANGEMODE_H
#define CONTACTILE_GRIPPER_MESSAGE_CHANGEMODE_H

#include <ros/service_traits.h>


#include <contactile_gripper/ChangeModeRequest.h>
#include <contactile_gripper/ChangeModeResponse.h>


namespace contactile_gripper
{

struct ChangeMode
{

typedef ChangeModeRequest Request;
typedef ChangeModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChangeMode
} // namespace contactile_gripper


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::contactile_gripper::ChangeMode > {
  static const char* value()
  {
    return "e1606556eb3ead28777d8c5a5ac25eb4";
  }

  static const char* value(const ::contactile_gripper::ChangeMode&) { return value(); }
};

template<>
struct DataType< ::contactile_gripper::ChangeMode > {
  static const char* value()
  {
    return "contactile_gripper/ChangeMode";
  }

  static const char* value(const ::contactile_gripper::ChangeMode&) { return value(); }
};


// service_traits::MD5Sum< ::contactile_gripper::ChangeModeRequest> should match
// service_traits::MD5Sum< ::contactile_gripper::ChangeMode >
template<>
struct MD5Sum< ::contactile_gripper::ChangeModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::contactile_gripper::ChangeMode >::value();
  }
  static const char* value(const ::contactile_gripper::ChangeModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::contactile_gripper::ChangeModeRequest> should match
// service_traits::DataType< ::contactile_gripper::ChangeMode >
template<>
struct DataType< ::contactile_gripper::ChangeModeRequest>
{
  static const char* value()
  {
    return DataType< ::contactile_gripper::ChangeMode >::value();
  }
  static const char* value(const ::contactile_gripper::ChangeModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::contactile_gripper::ChangeModeResponse> should match
// service_traits::MD5Sum< ::contactile_gripper::ChangeMode >
template<>
struct MD5Sum< ::contactile_gripper::ChangeModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::contactile_gripper::ChangeMode >::value();
  }
  static const char* value(const ::contactile_gripper::ChangeModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::contactile_gripper::ChangeModeResponse> should match
// service_traits::DataType< ::contactile_gripper::ChangeMode >
template<>
struct DataType< ::contactile_gripper::ChangeModeResponse>
{
  static const char* value()
  {
    return DataType< ::contactile_gripper::ChangeMode >::value();
  }
  static const char* value(const ::contactile_gripper::ChangeModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONTACTILE_GRIPPER_MESSAGE_CHANGEMODE_H
