// Generated by gencpp from file contactile_gripper/DataRecorder.msg
// DO NOT EDIT!


#ifndef CONTACTILE_GRIPPER_MESSAGE_DATARECORDER_H
#define CONTACTILE_GRIPPER_MESSAGE_DATARECORDER_H

#include <ros/service_traits.h>


#include <contactile_gripper/DataRecorderRequest.h>
#include <contactile_gripper/DataRecorderResponse.h>


namespace contactile_gripper
{

struct DataRecorder
{

typedef DataRecorderRequest Request;
typedef DataRecorderResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DataRecorder
} // namespace contactile_gripper


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::contactile_gripper::DataRecorder > {
  static const char* value()
  {
    return "86296c4752d7ffaaedf71fd495fe5e5f";
  }

  static const char* value(const ::contactile_gripper::DataRecorder&) { return value(); }
};

template<>
struct DataType< ::contactile_gripper::DataRecorder > {
  static const char* value()
  {
    return "contactile_gripper/DataRecorder";
  }

  static const char* value(const ::contactile_gripper::DataRecorder&) { return value(); }
};


// service_traits::MD5Sum< ::contactile_gripper::DataRecorderRequest> should match
// service_traits::MD5Sum< ::contactile_gripper::DataRecorder >
template<>
struct MD5Sum< ::contactile_gripper::DataRecorderRequest>
{
  static const char* value()
  {
    return MD5Sum< ::contactile_gripper::DataRecorder >::value();
  }
  static const char* value(const ::contactile_gripper::DataRecorderRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::contactile_gripper::DataRecorderRequest> should match
// service_traits::DataType< ::contactile_gripper::DataRecorder >
template<>
struct DataType< ::contactile_gripper::DataRecorderRequest>
{
  static const char* value()
  {
    return DataType< ::contactile_gripper::DataRecorder >::value();
  }
  static const char* value(const ::contactile_gripper::DataRecorderRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::contactile_gripper::DataRecorderResponse> should match
// service_traits::MD5Sum< ::contactile_gripper::DataRecorder >
template<>
struct MD5Sum< ::contactile_gripper::DataRecorderResponse>
{
  static const char* value()
  {
    return MD5Sum< ::contactile_gripper::DataRecorder >::value();
  }
  static const char* value(const ::contactile_gripper::DataRecorderResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::contactile_gripper::DataRecorderResponse> should match
// service_traits::DataType< ::contactile_gripper::DataRecorder >
template<>
struct DataType< ::contactile_gripper::DataRecorderResponse>
{
  static const char* value()
  {
    return DataType< ::contactile_gripper::DataRecorder >::value();
  }
  static const char* value(const ::contactile_gripper::DataRecorderResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONTACTILE_GRIPPER_MESSAGE_DATARECORDER_H
