// Generated by gencpp from file contactile_gripper/GripperChangeMode.msg
// DO NOT EDIT!


#ifndef CONTACTILE_GRIPPER_MESSAGE_GRIPPERCHANGEMODE_H
#define CONTACTILE_GRIPPER_MESSAGE_GRIPPERCHANGEMODE_H

#include <ros/service_traits.h>


#include <contactile_gripper/GripperChangeModeRequest.h>
#include <contactile_gripper/GripperChangeModeResponse.h>


namespace contactile_gripper
{

struct GripperChangeMode
{

typedef GripperChangeModeRequest Request;
typedef GripperChangeModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GripperChangeMode
} // namespace contactile_gripper


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::contactile_gripper::GripperChangeMode > {
  static const char* value()
  {
    return "e1606556eb3ead28777d8c5a5ac25eb4";
  }

  static const char* value(const ::contactile_gripper::GripperChangeMode&) { return value(); }
};

template<>
struct DataType< ::contactile_gripper::GripperChangeMode > {
  static const char* value()
  {
    return "contactile_gripper/GripperChangeMode";
  }

  static const char* value(const ::contactile_gripper::GripperChangeMode&) { return value(); }
};


// service_traits::MD5Sum< ::contactile_gripper::GripperChangeModeRequest> should match
// service_traits::MD5Sum< ::contactile_gripper::GripperChangeMode >
template<>
struct MD5Sum< ::contactile_gripper::GripperChangeModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::contactile_gripper::GripperChangeMode >::value();
  }
  static const char* value(const ::contactile_gripper::GripperChangeModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::contactile_gripper::GripperChangeModeRequest> should match
// service_traits::DataType< ::contactile_gripper::GripperChangeMode >
template<>
struct DataType< ::contactile_gripper::GripperChangeModeRequest>
{
  static const char* value()
  {
    return DataType< ::contactile_gripper::GripperChangeMode >::value();
  }
  static const char* value(const ::contactile_gripper::GripperChangeModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::contactile_gripper::GripperChangeModeResponse> should match
// service_traits::MD5Sum< ::contactile_gripper::GripperChangeMode >
template<>
struct MD5Sum< ::contactile_gripper::GripperChangeModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::contactile_gripper::GripperChangeMode >::value();
  }
  static const char* value(const ::contactile_gripper::GripperChangeModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::contactile_gripper::GripperChangeModeResponse> should match
// service_traits::DataType< ::contactile_gripper::GripperChangeMode >
template<>
struct DataType< ::contactile_gripper::GripperChangeModeResponse>
{
  static const char* value()
  {
    return DataType< ::contactile_gripper::GripperChangeMode >::value();
  }
  static const char* value(const ::contactile_gripper::GripperChangeModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONTACTILE_GRIPPER_MESSAGE_GRIPPERCHANGEMODE_H
