// Generated by gencpp from file contactile_gripper/Int32List.msg
// DO NOT EDIT!


#ifndef CONTACTILE_GRIPPER_MESSAGE_INT32LIST_H
#define CONTACTILE_GRIPPER_MESSAGE_INT32LIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace contactile_gripper
{
template <class ContainerAllocator>
struct Int32List_
{
  typedef Int32List_<ContainerAllocator> Type;

  Int32List_()
    : list()  {
    }
  Int32List_(const ContainerAllocator& _alloc)
    : list(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _list_type;
  _list_type list;





  typedef boost::shared_ptr< ::contactile_gripper::Int32List_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::contactile_gripper::Int32List_<ContainerAllocator> const> ConstPtr;

}; // struct Int32List_

typedef ::contactile_gripper::Int32List_<std::allocator<void> > Int32List;

typedef boost::shared_ptr< ::contactile_gripper::Int32List > Int32ListPtr;
typedef boost::shared_ptr< ::contactile_gripper::Int32List const> Int32ListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::contactile_gripper::Int32List_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::contactile_gripper::Int32List_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::contactile_gripper::Int32List_<ContainerAllocator1> & lhs, const ::contactile_gripper::Int32List_<ContainerAllocator2> & rhs)
{
  return lhs.list == rhs.list;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::contactile_gripper::Int32List_<ContainerAllocator1> & lhs, const ::contactile_gripper::Int32List_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace contactile_gripper

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::contactile_gripper::Int32List_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::contactile_gripper::Int32List_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::contactile_gripper::Int32List_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::contactile_gripper::Int32List_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::contactile_gripper::Int32List_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::contactile_gripper::Int32List_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::contactile_gripper::Int32List_<ContainerAllocator> >
{
  static const char* value()
  {
    return "33cd48253e96459f6910f32d963eda83";
  }

  static const char* value(const ::contactile_gripper::Int32List_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x33cd48253e96459fULL;
  static const uint64_t static_value2 = 0x6910f32d963eda83ULL;
};

template<class ContainerAllocator>
struct DataType< ::contactile_gripper::Int32List_<ContainerAllocator> >
{
  static const char* value()
  {
    return "contactile_gripper/Int32List";
  }

  static const char* value(const ::contactile_gripper::Int32List_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::contactile_gripper::Int32List_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] list\n"
;
  }

  static const char* value(const ::contactile_gripper::Int32List_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::contactile_gripper::Int32List_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Int32List_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::contactile_gripper::Int32List_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::contactile_gripper::Int32List_<ContainerAllocator>& v)
  {
    s << indent << "list[]" << std::endl;
    for (size_t i = 0; i < v.list.size(); ++i)
    {
      s << indent << "  list[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTACTILE_GRIPPER_MESSAGE_INT32LIST_H
