// Generated by gencpp from file contactile_gripper/StepperOff.msg
// DO NOT EDIT!


#ifndef CONTACTILE_GRIPPER_MESSAGE_STEPPEROFF_H
#define CONTACTILE_GRIPPER_MESSAGE_STEPPEROFF_H

#include <ros/service_traits.h>


#include <contactile_gripper/StepperOffRequest.h>
#include <contactile_gripper/StepperOffResponse.h>


namespace contactile_gripper
{

struct StepperOff
{

typedef StepperOffRequest Request;
typedef StepperOffResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StepperOff
} // namespace contactile_gripper


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::contactile_gripper::StepperOff > {
  static const char* value()
  {
    return "e1606556eb3ead28777d8c5a5ac25eb4";
  }

  static const char* value(const ::contactile_gripper::StepperOff&) { return value(); }
};

template<>
struct DataType< ::contactile_gripper::StepperOff > {
  static const char* value()
  {
    return "contactile_gripper/StepperOff";
  }

  static const char* value(const ::contactile_gripper::StepperOff&) { return value(); }
};


// service_traits::MD5Sum< ::contactile_gripper::StepperOffRequest> should match
// service_traits::MD5Sum< ::contactile_gripper::StepperOff >
template<>
struct MD5Sum< ::contactile_gripper::StepperOffRequest>
{
  static const char* value()
  {
    return MD5Sum< ::contactile_gripper::StepperOff >::value();
  }
  static const char* value(const ::contactile_gripper::StepperOffRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::contactile_gripper::StepperOffRequest> should match
// service_traits::DataType< ::contactile_gripper::StepperOff >
template<>
struct DataType< ::contactile_gripper::StepperOffRequest>
{
  static const char* value()
  {
    return DataType< ::contactile_gripper::StepperOff >::value();
  }
  static const char* value(const ::contactile_gripper::StepperOffRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::contactile_gripper::StepperOffResponse> should match
// service_traits::MD5Sum< ::contactile_gripper::StepperOff >
template<>
struct MD5Sum< ::contactile_gripper::StepperOffResponse>
{
  static const char* value()
  {
    return MD5Sum< ::contactile_gripper::StepperOff >::value();
  }
  static const char* value(const ::contactile_gripper::StepperOffResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::contactile_gripper::StepperOffResponse> should match
// service_traits::DataType< ::contactile_gripper::StepperOff >
template<>
struct DataType< ::contactile_gripper::StepperOffResponse>
{
  static const char* value()
  {
    return DataType< ::contactile_gripper::StepperOff >::value();
  }
  static const char* value(const ::contactile_gripper::StepperOffResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONTACTILE_GRIPPER_MESSAGE_STEPPEROFF_H
