// Generated by gencpp from file contactile_gripper/UIMenuRequest.msg
// DO NOT EDIT!


#ifndef CONTACTILE_GRIPPER_MESSAGE_UIMENUREQUEST_H
#define CONTACTILE_GRIPPER_MESSAGE_UIMENUREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace contactile_gripper
{
template <class ContainerAllocator>
struct UIMenuRequest_
{
  typedef UIMenuRequest_<ContainerAllocator> Type;

  UIMenuRequest_()
    : menu()  {
    }
  UIMenuRequest_(const ContainerAllocator& _alloc)
    : menu(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _menu_type;
  _menu_type menu;





  typedef boost::shared_ptr< ::contactile_gripper::UIMenuRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::contactile_gripper::UIMenuRequest_<ContainerAllocator> const> ConstPtr;

}; // struct UIMenuRequest_

typedef ::contactile_gripper::UIMenuRequest_<std::allocator<void> > UIMenuRequest;

typedef boost::shared_ptr< ::contactile_gripper::UIMenuRequest > UIMenuRequestPtr;
typedef boost::shared_ptr< ::contactile_gripper::UIMenuRequest const> UIMenuRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::contactile_gripper::UIMenuRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::contactile_gripper::UIMenuRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::contactile_gripper::UIMenuRequest_<ContainerAllocator1> & lhs, const ::contactile_gripper::UIMenuRequest_<ContainerAllocator2> & rhs)
{
  return lhs.menu == rhs.menu;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::contactile_gripper::UIMenuRequest_<ContainerAllocator1> & lhs, const ::contactile_gripper::UIMenuRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace contactile_gripper

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::contactile_gripper::UIMenuRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::contactile_gripper::UIMenuRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::contactile_gripper::UIMenuRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::contactile_gripper::UIMenuRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::contactile_gripper::UIMenuRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::contactile_gripper::UIMenuRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::contactile_gripper::UIMenuRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c203365aa9fc4c84f5cecbbb5ac3272a";
  }

  static const char* value(const ::contactile_gripper::UIMenuRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc203365aa9fc4c84ULL;
  static const uint64_t static_value2 = 0xf5cecbbb5ac3272aULL;
};

template<class ContainerAllocator>
struct DataType< ::contactile_gripper::UIMenuRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "contactile_gripper/UIMenuRequest";
  }

  static const char* value(const ::contactile_gripper::UIMenuRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::contactile_gripper::UIMenuRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string menu\n"
;
  }

  static const char* value(const ::contactile_gripper::UIMenuRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::contactile_gripper::UIMenuRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.menu);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UIMenuRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::contactile_gripper::UIMenuRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::contactile_gripper::UIMenuRequest_<ContainerAllocator>& v)
  {
    s << indent << "menu: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.menu);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTACTILE_GRIPPER_MESSAGE_UIMENUREQUEST_H
