// Generated by gencpp from file contactile_gripper/UIMenu.msg
// DO NOT EDIT!


#ifndef CONTACTILE_GRIPPER_MESSAGE_UIMENU_H
#define CONTACTILE_GRIPPER_MESSAGE_UIMENU_H

#include <ros/service_traits.h>


#include <contactile_gripper/UIMenuRequest.h>
#include <contactile_gripper/UIMenuResponse.h>


namespace contactile_gripper
{

struct UIMenu
{

typedef UIMenuRequest Request;
typedef UIMenuResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UIMenu
} // namespace contactile_gripper


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::contactile_gripper::UIMenu > {
  static const char* value()
  {
    return "c203365aa9fc4c84f5cecbbb5ac3272a";
  }

  static const char* value(const ::contactile_gripper::UIMenu&) { return value(); }
};

template<>
struct DataType< ::contactile_gripper::UIMenu > {
  static const char* value()
  {
    return "contactile_gripper/UIMenu";
  }

  static const char* value(const ::contactile_gripper::UIMenu&) { return value(); }
};


// service_traits::MD5Sum< ::contactile_gripper::UIMenuRequest> should match
// service_traits::MD5Sum< ::contactile_gripper::UIMenu >
template<>
struct MD5Sum< ::contactile_gripper::UIMenuRequest>
{
  static const char* value()
  {
    return MD5Sum< ::contactile_gripper::UIMenu >::value();
  }
  static const char* value(const ::contactile_gripper::UIMenuRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::contactile_gripper::UIMenuRequest> should match
// service_traits::DataType< ::contactile_gripper::UIMenu >
template<>
struct DataType< ::contactile_gripper::UIMenuRequest>
{
  static const char* value()
  {
    return DataType< ::contactile_gripper::UIMenu >::value();
  }
  static const char* value(const ::contactile_gripper::UIMenuRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::contactile_gripper::UIMenuResponse> should match
// service_traits::MD5Sum< ::contactile_gripper::UIMenu >
template<>
struct MD5Sum< ::contactile_gripper::UIMenuResponse>
{
  static const char* value()
  {
    return MD5Sum< ::contactile_gripper::UIMenu >::value();
  }
  static const char* value(const ::contactile_gripper::UIMenuResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::contactile_gripper::UIMenuResponse> should match
// service_traits::DataType< ::contactile_gripper::UIMenu >
template<>
struct DataType< ::contactile_gripper::UIMenuResponse>
{
  static const char* value()
  {
    return DataType< ::contactile_gripper::UIMenu >::value();
  }
  static const char* value(const ::contactile_gripper::UIMenuResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONTACTILE_GRIPPER_MESSAGE_UIMENU_H
