// Generated by gencpp from file contactile_gripper/UIMenuResponse.msg
// DO NOT EDIT!


#ifndef CONTACTILE_GRIPPER_MESSAGE_UIMENURESPONSE_H
#define CONTACTILE_GRIPPER_MESSAGE_UIMENURESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace contactile_gripper
{
template <class ContainerAllocator>
struct UIMenuResponse_
{
  typedef UIMenuResponse_<ContainerAllocator> Type;

  UIMenuResponse_()
    {
    }
  UIMenuResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::contactile_gripper::UIMenuResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::contactile_gripper::UIMenuResponse_<ContainerAllocator> const> ConstPtr;

}; // struct UIMenuResponse_

typedef ::contactile_gripper::UIMenuResponse_<std::allocator<void> > UIMenuResponse;

typedef boost::shared_ptr< ::contactile_gripper::UIMenuResponse > UIMenuResponsePtr;
typedef boost::shared_ptr< ::contactile_gripper::UIMenuResponse const> UIMenuResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::contactile_gripper::UIMenuResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::contactile_gripper::UIMenuResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace contactile_gripper

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::contactile_gripper::UIMenuResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::contactile_gripper::UIMenuResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::contactile_gripper::UIMenuResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::contactile_gripper::UIMenuResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::contactile_gripper::UIMenuResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::contactile_gripper::UIMenuResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::contactile_gripper::UIMenuResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::contactile_gripper::UIMenuResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::contactile_gripper::UIMenuResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "contactile_gripper/UIMenuResponse";
  }

  static const char* value(const ::contactile_gripper::UIMenuResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::contactile_gripper::UIMenuResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::contactile_gripper::UIMenuResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::contactile_gripper::UIMenuResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UIMenuResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::contactile_gripper::UIMenuResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::contactile_gripper::UIMenuResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // CONTACTILE_GRIPPER_MESSAGE_UIMENURESPONSE_H
